### ISSUE TITLE
Colorize never uses the same color/pattern for same project

### ISSUE THREAD

**Issue by petey** [jasonporritt/project-colorize#1]
I can reopen new atom instances with the same project and every time I get a different color/pattern. Was hoping that the color/pattern was consistent.

I'm not sure that the way the plugin gets the path is valid anymore. https://atom.io/docs/api/v0.148.0/Project

**Comment by jasonporritt** [comment]
The method for obtaining the path was updated to match Atom's new APIs. There is still a problem where the pattern is different the first time you open a directory, but after the first time the colors and patterns should be stable.

**Comment by petey** [comment]
👍
