### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kenhowardpdx** [jasonporritt/project-colorize#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/ken/.atom/packages/project-colorize/lib/project-colorize.coffee:6:9)
```

**Comment by dudektria** [comment]
+1

**Comment by ghost** [comment]
+1 for this

**Comment by adamnarkunskii** [comment]
https://github.com/jasonporritt/project-colorize/pull/3

**Comment by jasonporritt** [comment]
Merged wat-izz's pull request. Deprecation warnings are gone.
