### ISSUE TITLE
Ability to customize colors

### ISSUE THREAD

**Issue by kankaristo** [jasonporritt/project-colorize#5]
Thanks for a great package! This is a great way to quickly see which project's window I have open.

Would it be possible to customize the color (and pattern) manually?

Currently, my 2 main projects and my Atom config directory are all some shade of red or purple, which makes it a bit difficult to remember which is which. (~/.atom/ would ideally be green like the Atom logo, etc.)

Is the current color based on the project directory path?

Could this be changed to a configurable (initially random) string/number for each project path?

**Comment by ericcirone** [comment]
Would love options to specify what color per project also!

**Comment by kankaristo** [comment]
I took a look at the code and came up with this:

``` coffee
  module.exports =
    activate: (state) ->
-     pattern = GeoPattern.generate atom.project.getPaths().sort().join(':')
+     paths = atom.project.getPaths().sort().join(':')
+     string = atom.config.get("project-colorize." + paths)
+     if not string
+       atom.config.set("project-colorize." + paths, paths)
+       string = paths
+     pattern = GeoPattern.generate string

      style = document.createElement 'style'
      style.type = 'text/css'
      style.innerText =  '.tab-bar { background-image: ' + pattern.toDataUrl() + ';}'

      workspaceElement = atom.views.getView atom.workspace
      workspaceElement.appendChild style
```

It uses the same string as `project-colorize` currently uses, but also creates a config option for each project, which can then be customized.

This could be improved by adding observers for the config, because right now it requires restarting Atom for the pattern to update. I'm also not sure if all of the possible characters in a project's path are legal in a config option's name.

It might not be pretty, but it works. :)

**Comment by kankaristo** [comment]
I modified the code a bit and added config observers. There's a pull request at https://github.com/jasonporritt/project-colorize/pull/6.

I've been using the code in the pull request for a week or two, and it seems to be working quite well (better than I expected).
